JDP220602-21 task
piotr-grosicki/project-jdp-2206-02 pull request #35
Opened 2022-06-14 17:24 UTC by Huron007

2022-06-19 09:44 UTC, wgpdb approved these changes

2022-06-19 16:38 UTC, MoistAbes approved these changes

2022-06-19 20:11 UTC, KatarzynaKropiak approved these changes

2022-06-19 20:51 UTC, rapampamfau requested changes
Pod dodaniu @Builder do encji Product trzeba zmienić w testach tworzenie produktu bo inaczej się nie skompiluje

2022-06-20 11:37 UTC, rapampamfau approved these changes

2022-06-20 11:37 UTC, merged